### ISSUE TITLE
Add support for kubelet TLS bootstrapping

### ISSUE THREAD

**Issue by rothgar** [coreos/coreos-baremetal#399] opened 2016-12-12 18:08 UTC
There should be an optional install without needing to pre-create TLS certificates. The kubelet has the ability to bootstrap it's own TLS certificates via https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/kubelet-tls-bootstrap.md

Kubeadm already uses this to bootstrap a secure cluster.

Ignition should have examples on doing the same.

**Comment by crawford** [comment] 2016-12-12 18:14
Ignition doesn't know or care about application-specific (or even Container Linux-specific) options so I'm not sure what exactly you'd want in the Ignition documentation. Can you give me an example?

**Comment by dghubble** [comment] 2016-12-12 18:59
This is a duplicate of #393. Its not an Ignition-level example, but it makes sense within the coreos-baremetal family of reference clusters.

**Closed by dghubble** 2016-12-12 18:59 UTC
